image: Visual Studio 2019

environment:
  matrix:
    - nodejs_version: 14
      configuration: release
      platform: x64

install:
    # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
    - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
    - node --version
    - npm --version
    - npm install

build: off # because it is done in install

test_script:
  - npm test
