dist: trusty
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '7'
install:
- npm install
- npm install rollup -g
- travis_wait 20 npm install --only=dev
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  api_key:
    secure: ViV3PqZ/mCpNDdjy/o01Vsn5JcW94v8Rv6Ux/la1c8UGSu6qQdaCd4lq7d1mhLtDqCQvk+K6NmJXCaYZjd1CY1QSgv04XrSyi6+6CHAdKK/DFAqVz0G15qMe7/cakt7xkLce+r2za4bO2fhuLFAzfEiogs4dG/ZaXX8FXo6HfAweaGFvOdU4ClZYltFzkJI5VFOkSREH0GK9znuQlyFNR1Ybz2nP3mMu4A6f+OS1TkBeaGrJt0Lc4zvpELpW+EsJAg0rR937sUXIIG43NfDvUDwLAgO0pg6jTXhP5SMmKa9Abudd6i9Bh3Ayh4NGW23D7cPMVqJoUc0IiqT3VsN8x7YeudTVcHqCUu03K24vGafF3081+AuBLuZ3u3M9lmCXPwhBkuOj1blKvmPWu3skEIqeTjZ411FhE23w65njthSzhDUFxPGa+GNZX1l3XVPWREmLD51OkaAqdfbuRcaOKXoqIKXtZj0SQoMLUjFVYF0NIXHgvTcZ+FPG3zyz4qtO2ZF8hO+qlg5jB/watPzMqSNFvTx7lYJsBMFxi1oCpl2UYImfef9dt6jOGuR7gvEhAcyUMVawVh7MCQHX98hsOZ/WCezgBJFO27EW9F3dWobAUkS70PT7i0HOdzCfjF9s1a4OOTPXX9GI8SqN23y+ckCHPdwoB6GCJdbptL/Fg+w=
  on:
    tags: true
    repo: Nic30/d3-hwschematic
