dist: focal
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '14'
install:
- npm install --loglevel verbose
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  api_key:
    secure: w7VbtF83SGXA6Yq3ValX1Bmp2ieqDFw2RNksaQhCOCqBulVzYUSljdgnhZPomKaGw33Kcu87Q3n1lkfzFJZ1FlLurFM5NiEXNrKd/yhv7Fm4WGfTLPydH+6Z0E9dLVumhW0pdFEQPn8h7xXFeLkkdW2G2F6B9RVX5OVygvrfIUZpM+/ntORN82LCRJCSLzkIxz/mbrlGYvSvEjKELTPoDgmodHgQZLeNoc4jIRivFTg/+dctS1YLcGieYc2VhUZYZRj5ZXcuEZkHk0jcqdgmz0cr3xYXyKWxPT8QC9mw8ggzsxKNZQbmJ9VW/Sg3BV3B6SHAZ5oWHEMuS1WHkeWQojLHcjqnh0Gfk4Y02QzmhiKz5dbY1WI1dkA4WI0IV3ZKw1/tL1rJ6JM1BKqb0uzto99jfFs5oA/U60LtHvy4BXhiy4qEqxRDTk7cWSNb/V0vxU8CYR1KFBFquXOZEcfYBRBAI1YicBidOqX2E/HanW3yZN5IUOW1RASfsxoQfct55ah3mc19R1GCoeNaCcVMAywsPePI8sf3u/iSt+4g8IQ5hv9QGl4kfDwJ8glIUD2F0PLpNJt8Q/Ziw5Tq/1mg/haGkCqKfYwVp3OyC1G9aFak4MgQOhmtOjqqPirXf5z7ZWMh4aJjOj5bsnDgnMA1v8ue/MAiSKUMJD8TsXLCVZw=
  on:
    tags: true
    repo: Nic30/d3-hwschematic
