dist: trusty
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '7'
install:
- npm install --only=dev --loglevel info
- npm install
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  on:
    tags: true
    branch: master
  api_key:
    secure: d81+3KThRO/vZmGIRdYMZdbKEwav8FJBrsP+hyGVykAfPWJoAMNwq2TgXHEzTwnlH4S0i0UACB2/QX4IdPIj9WQvMTV8lRQOjpqDZsUEawCN6b1cYs/6kEs1jVH0REFjbOJI0eTsOKoY+1rJRp+yiF6KX1lK9Kl3SYgbgrYnUppNZsZxm4GfSTuLuPcilh3pEhm5OwsvhyXfzPM+zSgGCgi8pKLgsHk+ZRbtpHu8qJT2ySNwySSrMsh3CCGXhi267p/UsUMDvaLhLjTOAjk7asTezTJgSoSTPaiW28F7exAkVTOzJcKh2vysxK9ME9nKXZqelimbrCojVYP0mBY6tpaiYtqKX8PoXWbiLrCWozc1wn4QcGjVINc3PMf7JGXRG3mfJqSVNMVf1182moGQFo2GYzfZtMCBJdTQyRTkXqaCMvZ2gXkkKtgJ/AqPn/qyXjwDcU/LdOTE5ckzST6/KNOmgGmcm1IoeAeGdEf6W6uVACInp/Mup3fxTgpsegN+kHeULaujuY9LLuJtiP8dtHsv93nyRuxuIhmJr5Y93RR1Ns7/KGadocPTCHGglHht7/sdD2gTaFtv0EGcrC/7HgeYJhyMkfK4+M1oMPSVYWh/dPXUAZr3WAtEisv0zVJYFoM2U0w+kwqOTiQJIIqwZmkLgU4kUlQ7mVTfIQgMWso=
